name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened, ready_for_review ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.12.3' # Define the elixir version [required]
        otp-version: '23.2' # Define the OTP version [required]

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Check compiler warnings
      run: mix compile --warnings-as-errors

    - name: Run tests
      run: mix test
